#listener-configuration
flights.api.listener.host=localhost
flights.api.listener.port=8081
flights.api.listener.path=/abcd

#request-configuration
flights.api.http.request.host=training4-american-ws.cloudhub.io
flights.api.http.request.port=80
flights.api.http.request.path=/api/flights

#database-configiration
api.http.db.host=iltdb.learn.mulesoft.com
api.http.db.port=3306
api.http.db.user=mule
api.http.db.database=training